#!/bin/bash
git pull
make
datasets=("trackers.g" "soc-Journal.g" "dblp-author.g" "patentcite.g" "soc-pokec-relationships.g" "wikiTalk.g")

if [[ $1 == "" ]]; then
	./kcore Enron.g
elif [[ $1 == "all" ]]; then
	for ds in ${datasets[@]}; do
		echo "####### starting $ds ########"
		./kcore $ds
		echo "####### ended $ds ########"
	done
else
	./kcore ${datasets[$1]}
fi
